openapi: 3.0.3
info:
  contact:
    email: contact@mightycode.fr
    url: https://mightycode.fr/
  description: |
    This is a prototype of CPOO Project's front/back API.
  title: CPOO Server API
  version: 0.0.1
servers:
- url: http://localhost:8080/
security:
- CookieAuth: []
tags:
- description: User authentication.
  name: authentication
paths:
  /user/signup:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        "200":
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      security: []
      tags:
      - authentication
      x-content-type: application/json
      x-accepts: application/json
  /user/signin:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        "200":
          description: Success
          headers:
            Set-Cookie:
              explode: false
              schema:
                type: string
              style: simple
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      security: []
      tags:
      - authentication
      x-content-type: application/json
      x-accepts: application/json
  /user/signout:
    post:
      responses:
        "200":
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      tags:
      - authentication
      x-accepts: application/json
  /user/delete:
    post:
      responses:
        "200":
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      tags:
      - authentication
      x-accepts: application/json
  /user/forgotpwd:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPasswordDTO'
        required: true
      responses:
        "200":
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      tags:
      - forgot-pwd
      x-content-type: application/json
      x-accepts: application/json
  /user/settings:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettingsDTO'
          description: Successful response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Get user settings information
      tags:
      - user
      x-accepts: application/json
  /user/account/chgusername:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_user_account_chgusername_patch_request'
        required: true
      responses:
        "200":
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      tags:
      - account
      x-content-type: application/json
      x-accepts: application/json
  /user/account/changepp:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_user_account_changepp_patch_request'
        required: true
      responses:
        "200":
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      tags:
      - account
      x-content-type: application/json
      x-accepts: application/json
  /user/changepwd:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordDTO'
        required: true
      responses:
        "200":
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      tags:
      - change-pwd
      x-content-type: application/json
      x-accepts: application/json
  /user/disconnect:
    post:
      responses:
        "200":
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      tags:
      - account
      x-accepts: application/json
  /user/notifications:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationsDTO'
        required: true
      responses:
        "200":
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      tags:
      - notifications
      x-content-type: application/json
      x-accepts: application/json
  /user/change-theme:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_user_change_theme_patch_request'
        required: true
      responses:
        "200":
          description: Theme changed successfully
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Change user theme
      tags:
      - Appearance
      x-content-type: application/json
      x-accepts: application/json
  /user/language:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_user_language_patch_request'
        required: true
      responses:
        "200":
          description: Success
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      tags:
      - language
      x-content-type: application/json
      x-accepts: application/json
  /discussions/{username}:
    get:
      parameters:
      - explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/DiscussionDTO'
                type: array
          description: Successful response
      summary: Get a list of all discussions of a user
      tags:
      - messaging
      x-accepts: application/json
  /discussions/{discussion_id}/messages:
    get:
      parameters:
      - explode: false
        in: path
        name: discussion_id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/MessageDTO'
                type: array
          description: Successful response
      summary: Get all messages in a conversation
      tags:
      - messaging
      x-accepts: application/json
  /discussions/message:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostMessageDTO'
        required: true
      responses:
        "200":
          description: Message sent successfully
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Send a message in a disccusion
      tags:
      - messaging
      x-content-type: application/json
      x-accepts: application/json
  /discussions/create:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_discussions_create_post_request'
        required: true
      responses:
        "200":
          description: Conversation created successfully
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Error
      summary: Create a new discussion
      tags:
      - messaging
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    UserDTO:
      example:
        password: password
        email: email
        username: username
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
      type: object
    UserSettingsDTO:
      example:
        NotificationSound: true
        UnreadBadges: true
        theme: theme
        language: language
        profileImage: profileImage
      properties:
        theme:
          type: string
        language:
          type: string
        UnreadBadges:
          type: boolean
        NotificationSound:
          type: boolean
        profileImage:
          type: string
      type: object
    PostMessageDTO:
      description: Message to send
      example:
        to: bob@acme
        type: text/plain
        body: This is the message
      properties:
        to:
          example: bob@acme
          type: string
        type:
          example: text/plain
          format: mime
          type: string
        body:
          example: This is the message
          type: string
      required:
      - body
      - to
      - type
      type: object
    MessageDTO:
      allOf:
      - $ref: '#/components/schemas/PostMessageDTO'
      - properties:
          id:
            example: 667bdc23-3de4-482f-a0f4-3391452a7742
            format: uuid
            type: string
          timestamp:
            example: 1720294759999
            format: int64
            type: integer
          from:
            example: alice@acme
            type: string
        type: object
    DiscussionDTO:
      example:
        user1: user1
        user2: user2
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          format: uuid
          type: string
        user1:
          type: string
        user2:
          type: string
      type: object
    NewPasswordDTO:
      example:
        password: password
        code: 0
        email: email
        confirm-password: confirm-password
      properties:
        email:
          type: string
        code:
          type: integer
        password:
          type: string
        confirm-password:
          type: string
      type: object
    ChangePasswordDTO:
      example:
        old-password: old-password
        new-password: new-password
      properties:
        old-password:
          type: string
        new-password:
          type: string
      type: object
    NotificationsDTO:
      example:
        badges: badges
        sounds: sounds
      properties:
        sounds:
          type: string
        badges:
          type: string
      type: object
    ErrorDTO:
      properties:
        timestamp:
          type: string
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
      type: object
    _user_account_chgusername_patch_request:
      properties:
        username:
          type: string
      type: object
    _user_account_changepp_patch_request:
      properties:
        url:
          type: string
      type: object
    _user_change_theme_patch_request:
      properties:
        themeId:
          type: integer
      type: object
    _user_language_patch_request:
      properties:
        language:
          type: string
      type: object
    _discussions_create_post_request:
      properties:
        user1:
          type: string
        user2:
          type: string
      required:
      - user1
      - user2
      type: object
  securitySchemes:
    CookieAuth:
      description: Use a session cookie to authenticate (see /login).
      in: cookie
      name: JSESSIONID
      type: apiKey
x-samples-languages:
- curl
- javascript
- node
- java
- python
- php

