openapi: 3.0.3
info:
  contact:
    email: contact@mightycode.fr
    url: https://mightycode.fr/
  description: |
    This is a prototype of CPOO Project's front/back API.
  title: CPOO Server API
  version: 0.0.1
servers:
  - url: http://localhost:8080/
security:
  - CookieAuth: [ ]
tags:
  - name: authentication
    description: User authentication.
paths:
  /user/signup:
    post:
      security: [ ]
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/signin:
    post:
      security: [ ]
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: Success
          headers:
            Set-Cookie:
              schema:
                type: string
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/signout:
    post:
      tags:
        - authentication
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/delete:
    post:
      tags:
        - authentication
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/forgotpwd:
    post:
      tags : 
       - forgot-pwd
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/NewPasswordDTO'
                  
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/settings:
    get:
      tags:
        - user
      summary: Get user settings information
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettingsDTO'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/account/chgusername:
    patch:
      tags:
        - account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/account/changepp:
    patch:
      tags:
        - account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

  /user/changepwd:
    patch:
      tags : 
       - change-pwd
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/ChangePasswordDTO'
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/disconnect:
    post:
      tags:
        - account
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/notifications:
    patch:
      tags:
        - notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/NotificationsDTO'
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

  /user/change-theme:
    patch:
      tags:
        - Appearance
      summary: Change user theme
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                themeId:
                  type: integer
      responses:
        '200':
          description: Theme changed successfully
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /user/language:
    patch:
      tags:
        - language
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                language:
                  type: string
      responses:
        '200':
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

  /discussions/{username}:
    get:
      tags:
        - messaging
      summary: Get a list of all discussions of a user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DiscussionDTO'
                  
  /discussions/{discussion_id}/messages:
    get:
      tags:
        - messaging
      summary: Get all messages in a conversation
      parameters:
        - name: discussion_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MessageDTO'
    post:
      tags:
        - messaging
      summary: Send a message in a disccusion
      parameters:
        - name: discussion_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageDTO'
      responses:
        '200':
          description: Message sent successfully
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /discussions/create:
    post:
      tags:
        - messaging
      summary: Create a new discussion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user1:
                  type: string
                user2:
                  type: string
              required:
                - user1
                - user2
      responses:
        '200':
          description: Conversation created successfully
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
components:
  schemas:
    UserDTO:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    UserSettingsDTO:
      type: object
      properties:
        theme:
          type: string
        language:
          type: string
        UnreadBadges:
          type: boolean
        NotificationSound:
          type: boolean
        profileImage:
          type: string
    MessageDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
        sender:
          type: string
        timestamp:
          type: string
    DiscussionDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user1:
          type: string
        user2:
          type: string
    NewPasswordDTO:
      type : object
      properties :
        email:
          type : string
        code :
          type : integer
        password :
          type : string
        confirm-password : 
          type : string
    ChangePasswordDTO:
      type : object
      properties :
        old-password:
          type : string
        new-password : 
          type : string
    NotificationsDTO:
      type: object
      properties:
        sounds:
          type: string
        badges:
          type: string
    ErrorDTO:
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID
      description: Use a session cookie to authenticate (see /login).
x-samples-languages:
  - curl
  - javascript
  - node
  - java
  - python
  - php
